# example.toml

[window]
width  = 3840999
height = 2""160

[capture]
frames = true
png    = true
bmp    = false   # your loader also accepts legacy "cpature_bmp" on read

[le]
halfLife        = 0.014
bloomThreshold  = 1.4
bloomSoftKnee   = 0.7
bloomStrength   = 2.0
bloomIterations = 6
exposure        = 1.4
gamma           = 2.2
brightness      = 0.0
contrast        = 1.0
saturation      = 1.0
msaaSamples     = 8

[camera.start]
pos   = [0.0, 1.5, 3.0]
yaw   = 15.0
pitch = -5.0
fov   = 45.0

[camera.end]
pos   = [1.0, 1.5, 2.5]
yaw   = 25.0
pitch = -10.0
fov   = 45.0

# ---------------- Shader 0 ----------------
[[shaders]]
vertex   = "shaders/tri.vs"
fragment = "shaders/tri.fs"

  # Instance 0
  [[shaders.instances]]
  uniforms_start = [0,0,0,0,0,0,0,0,0,0]   # u0..u9
  uniforms_end   = [1,1,1,1,1,1,1,1,1,1]

  [shaders.instances.transform_start]
  position = [0.0, 0.0, 0.0]
  euler    = [0.0, 0.0, 0.0]
  scale    = [1.0, 1.0, 1.0]

  [shaders.instances.transform_end]
  position = [0.0, 0.0, 0.0]
  euler    = [0.0, 0.0, 0.0]
  scale    = [1.0, 1.0, 1.0]

  group_size = [1000, 1000, 1]
  number_of_drawcalls = 4

  # Instance 1
  [[shaders.instances]]
  uniforms_start = [0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2]
  uniforms_end   = [0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8]

  [shaders.instances.transform_start]
  position = [0.0, 0.0, 0.0]
  euler    = [10.0, 0.0, 0.0]
  scale    = [1.0, 1.0, 1.0]

  [shaders.instances.transform_end]
  position = [0.0, 0.0, 0.0]
  euler    = [0.0, 0.0, 0.0]
  scale    = [1.0, 1.0, 1.0]

  group_size = [512, 512, 1]
  number_of_drawcalls = 2

# ---------------- Shader 1 ----------------
[[shaders]]
vertex   = "shaders/quad.vs"
fragment = "shaders/blur.fs"

  [[shaders.instances]]
  uniforms_start = [0,0,0,0,0,0,0,0,0,0]
  uniforms_end   = [0,0,0,0,0,0,0,0,0,0]

  [shaders.instances.transform_start]
  position = [0.0, 0.0, 0.0]
  euler    = [0.0, 0.0, 0.0]
  scale    = [1.0, 1.0, 1.0]

  [shaders.instances.transform_end]
  position = [0.0, 0.0, 0.0]
  euler    = [0.0, 0.0, 0.0]
  scale    = [1.0, 1.0, 1.0]

  group_size = [1024, 1024, 1]
  number_of_drawcalls = 1
